export const PRODUCT_LIST_REQUEST = 'PORDUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PORDUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PORDUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PORDUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PORDUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PORDUCT_DETAILS_FAIL';