const data = {
    products: [
      {
        _id: '1',
        name: 'Sunset Palm Shirt',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 125000,
        countInStock: 100,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Black Fit Sweater',
        category: 'Shirts',
        image: '/images/p2.jpg',
        price: 100000,
        countInStock: 100,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Lacoste Jeans',
        category: 'Shirts',
        image: '/images/p3.jpg',
        price: 220000,
        countInStock: 0,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Pigeon Sweater',
        category: 'Pants',
        image: '/images/p4.jpg',
        price: 120000,
        countInStock: 100,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'High Pants',
        category: 'Pants',
        image: '/images/p5.jpg',
        price: 150000,
        countInStock: 100,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Sweatshirt',
        category: 'Pants',
        image: '/images/p6.jpg',
        price: 200000,
        countInStock: 100,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;